name: ROBO

on:
  schedule:
    - cron: "45 1,13 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ETAPA-1 Extrair dados da WEB
      env:
         API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
         echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
         chmod +x ./updater/extrator_queimadas.py
         ./updater/extrator_queimadas.py
    - name: ETAPA-2 Atualizar dados para o repositorio
      uses: test-room-7/action-update-file@v1.5.0
      with:
        file-path: data/*.csv
        commit-msg: Atualizar csv de ${{ env.MY_DATE }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
